version: "3.8"

services:
  web:
    build: back
    restart: always
    ports:
      - '8000:8000'
  front:
    build: front
    restart: always
    ports:
      - '3060:3000'
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
      REACT_APP_API_BASE: ${REACT_APP_API_BASE}
      API_URL: ${API_URL}
